import { CustomerMetric, NUMBER_OPERATORS } from '../domain/metric.types';

/** Temporary frontend/mock enum contracts. Backend may replace these later. */
export const TRIAL_STATUS_VALUES = [
  { value: 'in_trial', label: 'In trial' },
  { value: 'trial_expired', label: 'Trial expired' },
  { value: 'not_in_trial', label: 'Not in trial' },
] as const;

export const ACCOUNT_STATUS_VALUES = [
  { value: 'trial', label: 'Trial' },
  { value: 'active', label: 'Active' },
  { value: 'past_due', label: 'Past due' },
  { value: 'cancelled', label: 'Cancelled' },
  { value: 'inactive', label: 'Inactive' },
] as const;

const DATE_OCCURRENCE_OPERATORS = ['is_empty'] as const;

/**
 * `lastPortalSignInAt`, `daysSinceLastPortalSignIn`, and `portalSignInCount`
 * are subscriber/admin activity (signing into Portal Genie), not client
 * portal usage. Keys are preserved so existing fixture rules keep loading.
 * Client portal behaviour uses the separate `hasPortalVisit` family.
 */
export const METRIC_CATALOG: readonly CustomerMetric[] = [
  {
    key: 'registeredAt',
    displayName: 'Registration date',
    category: 'lifecycle',
    type: 'date',
    operators: DATE_OCCURRENCE_OPERATORS,
    valueRequired: false,
    supportsTimingAnchor: true,
    timingDirections: ['after'],
  },
  {
    key: 'daysSinceRegistration',
    displayName: 'Days since registration',
    category: 'lifecycle',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'trialStatus',
    displayName: 'Trial status',
    category: 'lifecycle',
    type: 'enum',
    operators: ['is', 'is_not'],
    valueRequired: true,
    enumValues: TRIAL_STATUS_VALUES,
    supportsTimingAnchor: false,
  },
  {
    key: 'trialExpiresAt',
    displayName: 'Trial expiry date',
    category: 'lifecycle',
    type: 'date',
    operators: DATE_OCCURRENCE_OPERATORS,
    valueRequired: false,
    supportsTimingAnchor: true,
    timingDirections: ['after', 'before'],
  },
  {
    key: 'daysUntilTrialExpiry',
    displayName: 'Days until trial expiry',
    category: 'lifecycle',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'accountStatus',
    displayName: 'Account / subscription status',
    category: 'lifecycle',
    type: 'enum',
    operators: ['is', 'is_not'],
    valueRequired: true,
    enumValues: ACCOUNT_STATUS_VALUES,
    supportsTimingAnchor: false,
  },
  {
    key: 'logoUploaded',
    displayName: 'Logo uploaded',
    description: 'whether a logo has been uploaded',
    category: 'branding',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'lastPortalSignInAt',
    displayName: 'Admin sign-in',
    category: 'admin_activity',
    type: 'date',
    operators: DATE_OCCURRENCE_OPERATORS,
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'daysSinceLastPortalSignIn',
    displayName: 'Days since last admin sign-in',
    category: 'admin_activity',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'portalSignInCount',
    displayName: 'Admin sign-in count',
    category: 'admin_activity',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasCreatedFolder',
    displayName: 'Folder',
    description: 'whether at least one folder has been created',
    category: 'admin_activity',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'folderCount',
    displayName: 'Folder count',
    category: 'admin_activity',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasUploadedDocument',
    displayName: 'Document',
    description: 'whether at least one document has been uploaded',
    category: 'admin_activity',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'documentCount',
    displayName: 'Document count',
    category: 'admin_activity',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'lastDocumentUploadedAt',
    displayName: 'Last document uploaded',
    category: 'admin_activity',
    type: 'date',
    operators: DATE_OCCURRENCE_OPERATORS,
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'daysSinceLastDocumentUpload',
    displayName: 'Days since last document upload',
    category: 'admin_activity',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'accountingSoftwareConnected',
    displayName: 'Accounting software',
    description: 'whether accounting software is connected',
    category: 'admin_activity',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasPortalVisit',
    displayName: 'Portal visit',
    description: 'whether a client has visited the portal',
    category: 'portal_usage',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'daysSinceLastPortalVisit',
    displayName: 'Days since last portal visit',
    category: 'portal_usage',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'portalVisitCount',
    displayName: 'Portal visit count',
    category: 'portal_usage',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasPortalDocumentUpload',
    displayName: 'Portal document upload',
    description: 'whether a client has uploaded a document',
    category: 'portal_usage',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'portalDocumentUploadCount',
    displayName: 'Portal document upload count',
    category: 'portal_usage',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'lastPortalDocumentUploadedAt',
    displayName: 'Last portal document uploaded',
    category: 'portal_usage',
    type: 'date',
    operators: DATE_OCCURRENCE_OPERATORS,
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'daysSinceLastPortalDocumentUpload',
    displayName: 'Days since last portal document upload',
    category: 'portal_usage',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasCreatedScheduledEmailTemplate',
    displayName: 'Scheduled email template',
    description: 'whether a scheduled email template has been created',
    category: 'communications',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
];
