import { CustomerMetric, NUMBER_OPERATORS } from '../domain/metric.types';

/** Temporary frontend/mock enum contracts. Backend may replace these later. */
export const TRIAL_STATUS_VALUES = [
  { value: 'in_trial', label: 'In trial' },
  { value: 'trial_expired', label: 'Trial expired' },
  { value: 'not_in_trial', label: 'Not in trial' },
] as const;

export const ACCOUNT_STATUS_VALUES = [
  { value: 'trial', label: 'Trial' },
  { value: 'active', label: 'Active' },
  { value: 'past_due', label: 'Past due' },
  { value: 'cancelled', label: 'Cancelled' },
  { value: 'inactive', label: 'Inactive' },
] as const;

export const METRIC_CATALOG: readonly CustomerMetric[] = [
  {
    key: 'registeredAt',
    displayName: 'Registration date',
    category: 'lifecycle',
    type: 'date',
    operators: ['is_empty'],
    valueRequired: false,
    supportsTimingAnchor: true,
    timingDirections: ['after'],
  },
  {
    key: 'daysSinceRegistration',
    displayName: 'Days since registration',
    category: 'lifecycle',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'trialStatus',
    displayName: 'Trial status',
    category: 'lifecycle',
    type: 'enum',
    operators: ['is', 'is_not'],
    valueRequired: true,
    enumValues: TRIAL_STATUS_VALUES,
    supportsTimingAnchor: false,
  },
  {
    key: 'trialExpiresAt',
    displayName: 'Trial expiry date',
    category: 'lifecycle',
    type: 'date',
    operators: ['is_empty'],
    valueRequired: false,
    supportsTimingAnchor: true,
    timingDirections: ['after', 'before'],
  },
  {
    key: 'daysUntilTrialExpiry',
    displayName: 'Days until trial expiry',
    category: 'lifecycle',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'accountStatus',
    displayName: 'Account / subscription status',
    category: 'lifecycle',
    type: 'enum',
    operators: ['is', 'is_not'],
    valueRequired: true,
    enumValues: ACCOUNT_STATUS_VALUES,
    supportsTimingAnchor: false,
  },
  {
    key: 'logoUploaded',
    displayName: 'Logo uploaded',
    description: 'whether a logo has been uploaded',
    category: 'branding',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'lastPortalSignInAt',
    displayName: 'Last portal sign-in',
    description: 'whether the customer has ever signed in',
    category: 'activity',
    type: 'date',
    operators: ['is_empty'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'daysSinceLastPortalSignIn',
    displayName: 'Days since last portal sign-in',
    category: 'activity',
    type: 'duration_days',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'portalSignInCount',
    displayName: 'Portal sign-in count',
    category: 'activity',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'folderCount',
    displayName: 'Folder count',
    category: 'content',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasCreatedFolder',
    displayName: 'Has created a folder',
    description: 'whether at least one folder has been created',
    category: 'content',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
  {
    key: 'documentCount',
    displayName: 'Document count',
    category: 'content',
    type: 'number',
    operators: NUMBER_OPERATORS,
    valueRequired: true,
    supportsTimingAnchor: false,
  },
  {
    key: 'hasUploadedDocument',
    displayName: 'Has uploaded a document',
    description: 'whether at least one document has been uploaded',
    category: 'content',
    type: 'boolean',
    operators: ['is_true', 'is_false'],
    valueRequired: false,
    supportsTimingAnchor: false,
  },
];
