export const COMMUNICATION_CATEGORIES = [
    'welcome',
    'onboarding',
    'setup',
    'branding',
    'folder_adoption',
    'document_adoption',
    'inactivity',
    'trial_reminder',
    'trial_expiry',
    'announcement',
    'milestone',
];
export const COMMUNICATION_CATEGORY_LABELS = {
    welcome: 'Welcome',
    onboarding: 'Onboarding',
    setup: 'Setup',
    branding: 'Branding / logo adoption',
    folder_adoption: 'Folder adoption',
    document_adoption: 'Document adoption',
    inactivity: 'Inactivity / re-engagement',
    trial_reminder: 'Trial reminders',
    trial_expiry: 'Trial expiry',
    announcement: 'Product / feature announcements',
    milestone: 'Customer milestones',
};
